# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 768)
        MainWindow.setStyleSheet("background: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.data_frame = QtWidgets.QFrame(self.centralwidget)
        self.data_frame.setGeometry(QtCore.QRect(256, 15, 768, 461))
        self.data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_frame.setObjectName("data_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.data_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 751, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.EQ_label = QtWidgets.QLabel(self.data_frame)
        self.EQ_label.setEnabled(True)
        self.EQ_label.setGeometry(QtCore.QRect(334, 5, 100, 31))
        self.EQ_label.setStyleSheet("background: gray;\n"
"font: 14pt \"Arial\";\n"
"")
        self.EQ_label.setAlignment(QtCore.Qt.AlignCenter)
        self.EQ_label.setObjectName("EQ_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.data_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 751, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LRframe = QtWidgets.QFrame(self.centralwidget)
        self.LRframe.setGeometry(QtCore.QRect(256, 480, 768, 80))
        self.LRframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LRframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LRframe.setObjectName("LRframe")
        self.LRSlider = QtWidgets.QSlider(self.LRframe)
        self.LRSlider.setGeometry(QtCore.QRect(34, 47, 700, 22))
        self.LRSlider.setMaximum(4)
        self.LRSlider.setProperty("value", 2)
        self.LRSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LRSlider.setObjectName("LRSlider")
        self.label_L = QtWidgets.QLabel(self.LRframe)
        self.label_L.setGeometry(QtCore.QRect(34, 13, 16, 16))
        self.label_L.setObjectName("label_L")
        self.label_R = QtWidgets.QLabel(self.LRframe)
        self.label_R.setGeometry(QtCore.QRect(718, 13, 16, 16))
        self.label_R.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_R.setObjectName("label_R")
        self.play_frame = QtWidgets.QFrame(self.centralwidget)
        self.play_frame.setGeometry(QtCore.QRect(0, 597, 1280, 121))
        self.play_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.play_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.play_frame.setObjectName("play_frame")
        self.progressSlider = QtWidgets.QSlider(self.play_frame)
        self.progressSlider.setGeometry(QtCore.QRect(30, 70, 1100, 50))
        self.progressSlider.setStyleSheet("QSlider::handle:horizontal {\n"
"background: white;\n"
"border: 6px solid green;\n"
"width: 8px;\n"
"height: 8px;\n"
"border-radius:10px;\n"
"margin: -6px 0px -6px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"height: 8px;\n"
"background: gray;\n"
"border: 1px solid black;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"height: 8px;\n"
"background: gray;\n"
"border: 1px solid black;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"height: 8px;\n"
"background: green;\n"
"border: 1px solid black;\n"
"border-radius:4px;\n"
"}")
        self.progressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.progressSlider.setObjectName("progressSlider")
        self.progressLabel = QtWidgets.QLabel(self.play_frame)
        self.progressLabel.setGeometry(QtCore.QRect(1147, 85, 91, 16))
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.play_button = QtWidgets.QPushButton(self.play_frame)
        self.play_button.setGeometry(QtCore.QRect(625, 30, 32, 32))
        self.play_button.setStyleSheet("background: rgb(222, 222, 222);")
        self.play_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon)
        self.play_button.setObjectName("play_button")
        self.stop_button = QtWidgets.QPushButton(self.play_frame)
        self.stop_button.setGeometry(QtCore.QRect(550, 30, 32, 32))
        self.stop_button.setStyleSheet("background: rgb(222, 222, 222);")
        self.stop_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon1)
        self.stop_button.setObjectName("stop_button")
        self.pause_button = QtWidgets.QPushButton(self.play_frame)
        self.pause_button.setGeometry(QtCore.QRect(700, 30, 32, 32))
        self.pause_button.setStyleSheet("background: rgb(222, 222, 222);")
        self.pause_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_button.setIcon(icon2)
        self.pause_button.setObjectName("pause_button")
        self.song_name_label = QtWidgets.QLabel(self.play_frame)
        self.song_name_label.setGeometry(QtCore.QRect(900, 10, 361, 16))
        self.song_name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.song_name_label.setObjectName("song_name_label")
        self.volume_slider = QtWidgets.QSlider(self.play_frame)
        self.volume_slider.setGeometry(QtCore.QRect(50, 22, 101, 50))
        self.volume_slider.setStyleSheet("QSlider::handle:horizontal {\n"
"background: white;\n"
"border: 4px solid green;\n"
"width: 8px;\n"
"height: 8px;\n"
"border-radius:8px;\n"
"margin: -5px 0px -5px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"height: 6px;\n"
"background: gray;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"height: 6px;\n"
"background: gray;\n"
"border: 1px solid black;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"height: 6px;\n"
"background: green;\n"
"border: 1px solid black;\n"
"border-radius: 2px;\n"
"}")
        self.volume_slider.setMaximum(100)
        self.volume_slider.setProperty("value", 100)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.sound_button = QtWidgets.QPushButton(self.play_frame)
        self.sound_button.setGeometry(QtCore.QRect(170, 30, 32, 32))
        self.sound_button.setStyleSheet("background: rgb(222, 222, 222);")
        self.sound_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/sound_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_button.setIcon(icon3)
        self.sound_button.setIconSize(QtCore.QSize(32, 32))
        self.sound_button.setObjectName("sound_button")
        self.filebutton = QtWidgets.QPushButton(self.play_frame)
        self.filebutton.setGeometry(QtCore.QRect(892, 40, 93, 28))
        self.filebutton.setStyleSheet("background: rgb(222, 222, 222);\n"
"")
        self.filebutton.setObjectName("filebutton")
        self.NG_frame = QtWidgets.QFrame(self.centralwidget)
        self.NG_frame.setGeometry(QtCore.QRect(0, 15, 256, 291))
        self.NG_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NG_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NG_frame.setObjectName("NG_frame")
        self.NG_label = QtWidgets.QLabel(self.NG_frame)
        self.NG_label.setGeometry(QtCore.QRect(68, 5, 120, 30))
        self.NG_label.setStyleSheet("background: gray;\n"
"font: 14pt \"Arial\";\n"
"")
        self.NG_label.setAlignment(QtCore.Qt.AlignCenter)
        self.NG_label.setObjectName("NG_label")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.NG_frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 241, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_NG = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_NG.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_NG.setObjectName("verticalLayout_NG")
        self.Comp_frame = QtWidgets.QFrame(self.centralwidget)
        self.Comp_frame.setGeometry(QtCore.QRect(1024, 15, 256, 291))
        self.Comp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Comp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Comp_frame.setObjectName("Comp_frame")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Comp_frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 241, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_Comp = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_Comp.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Comp.setObjectName("verticalLayout_Comp")
        self.Comp_label = QtWidgets.QLabel(self.Comp_frame)
        self.Comp_label.setGeometry(QtCore.QRect(63, 5, 130, 30))
        self.Comp_label.setStyleSheet("background: gray;\n"
"font: 14pt \"Arial\";\n"
"")
        self.Comp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_label.setObjectName("Comp_label")
        self.NG_parameter_frame = QtWidgets.QFrame(self.centralwidget)
        self.NG_parameter_frame.setGeometry(QtCore.QRect(20, 310, 220, 250))
        self.NG_parameter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NG_parameter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NG_parameter_frame.setObjectName("NG_parameter_frame")
        self.NG_threshold_slider = QtWidgets.QSlider(self.NG_parameter_frame)
        self.NG_threshold_slider.setGeometry(QtCore.QRect(100, 50, 22, 160))
        self.NG_threshold_slider.setMaximum(90)
        self.NG_threshold_slider.setOrientation(QtCore.Qt.Vertical)
        self.NG_threshold_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.NG_threshold_slider.setTickInterval(10)
        self.NG_threshold_slider.setObjectName("NG_threshold_slider")
        self.ND_threshold_label = QtWidgets.QLabel(self.NG_parameter_frame)
        self.ND_threshold_label.setGeometry(QtCore.QRect(84, 220, 58, 15))
        self.ND_threshold_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ND_threshold_label.setObjectName("ND_threshold_label")
        self.dB_NG = QtWidgets.QLabel(self.NG_parameter_frame)
        self.dB_NG.setGeometry(QtCore.QRect(120, 20, 20, 22))
        self.dB_NG.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_NG.setObjectName("dB_NG")
        self.NG_threshold_lineEdit = QtWidgets.QLineEdit(self.NG_parameter_frame)
        self.NG_threshold_lineEdit.setGeometry(QtCore.QRect(100, 20, 21, 22))
        self.NG_threshold_lineEdit.setStyleSheet("border: 0px;\n"
"")
        self.NG_threshold_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.NG_threshold_lineEdit.setObjectName("NG_threshold_lineEdit")
        self.Comp__parameter_frame = QtWidgets.QFrame(self.centralwidget)
        self.Comp__parameter_frame.setGeometry(QtCore.QRect(1040, 310, 220, 250))
        self.Comp__parameter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Comp__parameter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Comp__parameter_frame.setObjectName("Comp__parameter_frame")
        self.Comp_threshold_slider = QtWidgets.QSlider(self.Comp__parameter_frame)
        self.Comp_threshold_slider.setGeometry(QtCore.QRect(30, 50, 22, 160))
        self.Comp_threshold_slider.setMaximum(90)
        self.Comp_threshold_slider.setProperty("value", 90)
        self.Comp_threshold_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Comp_threshold_slider.setTickInterval(10)
        self.Comp_threshold_slider.setObjectName("Comp_threshold_slider")
        self.Comp_ratio_slider = QtWidgets.QSlider(self.Comp__parameter_frame)
        self.Comp_ratio_slider.setGeometry(QtCore.QRect(100, 50, 22, 160))
        self.Comp_ratio_slider.setMinimum(1)
        self.Comp_ratio_slider.setMaximum(31)
        self.Comp_ratio_slider.setPageStep(1)
        self.Comp_ratio_slider.setProperty("value", 5)
        self.Comp_ratio_slider.setOrientation(QtCore.Qt.Vertical)
        self.Comp_ratio_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Comp_ratio_slider.setTickInterval(5)
        self.Comp_ratio_slider.setObjectName("Comp_ratio_slider")
        self.Comp_makeup_slider = QtWidgets.QSlider(self.Comp__parameter_frame)
        self.Comp_makeup_slider.setGeometry(QtCore.QRect(170, 50, 22, 160))
        self.Comp_makeup_slider.setMinimum(0)
        self.Comp_makeup_slider.setMaximum(10)
        self.Comp_makeup_slider.setSingleStep(1)
        self.Comp_makeup_slider.setProperty("value", 0)
        self.Comp_makeup_slider.setOrientation(QtCore.Qt.Vertical)
        self.Comp_makeup_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.Comp_makeup_slider.setTickInterval(5)
        self.Comp_makeup_slider.setObjectName("Comp_makeup_slider")
        self.Comp_threshold_label = QtWidgets.QLabel(self.Comp__parameter_frame)
        self.Comp_threshold_label.setGeometry(QtCore.QRect(13, 220, 58, 15))
        self.Comp_threshold_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_threshold_label.setObjectName("Comp_threshold_label")
        self.Comp_ratio_label = QtWidgets.QLabel(self.Comp__parameter_frame)
        self.Comp_ratio_label.setGeometry(QtCore.QRect(83, 220, 58, 15))
        self.Comp_ratio_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_ratio_label.setObjectName("Comp_ratio_label")
        self.Comp_makeup_label = QtWidgets.QLabel(self.Comp__parameter_frame)
        self.Comp_makeup_label.setGeometry(QtCore.QRect(153, 220, 58, 15))
        self.Comp_makeup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_makeup_label.setObjectName("Comp_makeup_label")
        self.Comp_threshold_lineEdit = QtWidgets.QLineEdit(self.Comp__parameter_frame)
        self.Comp_threshold_lineEdit.setGeometry(QtCore.QRect(30, 20, 21, 22))
        self.Comp_threshold_lineEdit.setStyleSheet("border: 0px;\n"
"")
        self.Comp_threshold_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_threshold_lineEdit.setObjectName("Comp_threshold_lineEdit")
        self.dB_Comp = QtWidgets.QLabel(self.Comp__parameter_frame)
        self.dB_Comp.setGeometry(QtCore.QRect(50, 20, 20, 22))
        self.dB_Comp.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_Comp.setObjectName("dB_Comp")
        self.Comp_ratio_lineEdit = QtWidgets.QLineEdit(self.Comp__parameter_frame)
        self.Comp_ratio_lineEdit.setGeometry(QtCore.QRect(95, 20, 31, 22))
        self.Comp_ratio_lineEdit.setStyleSheet("border: 0px;\n"
"")
        self.Comp_ratio_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_ratio_lineEdit.setObjectName("Comp_ratio_lineEdit")
        self.Comp_makeup_lineEdit = QtWidgets.QLineEdit(self.Comp__parameter_frame)
        self.Comp_makeup_lineEdit.setGeometry(QtCore.QRect(166, 20, 31, 22))
        self.Comp_makeup_lineEdit.setStyleSheet("border: 0px;\n"
"")
        self.Comp_makeup_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Comp_makeup_lineEdit.setObjectName("Comp_makeup_lineEdit")
        self.dB_Comp_2 = QtWidgets.QLabel(self.Comp__parameter_frame)
        self.dB_Comp_2.setGeometry(QtCore.QRect(190, 20, 20, 22))
        self.dB_Comp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_Comp_2.setObjectName("dB_Comp_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EQ_label.setText(_translate("MainWindow", "Equalizer"))
        self.label_L.setText(_translate("MainWindow", "L"))
        self.label_R.setText(_translate("MainWindow", "R"))
        self.progressLabel.setText(_translate("MainWindow", "XX:XX/XX:XX"))
        self.song_name_label.setText(_translate("MainWindow", "Now Playing:"))
        self.filebutton.setText(_translate("MainWindow", "choose file"))
        self.NG_label.setText(_translate("MainWindow", "Noise Gate"))
        self.Comp_label.setText(_translate("MainWindow", "Compressor"))
        self.ND_threshold_label.setText(_translate("MainWindow", "threshold"))
        self.dB_NG.setText(_translate("MainWindow", "dB"))
        self.NG_threshold_lineEdit.setText(_translate("MainWindow", "0"))
        self.Comp_threshold_label.setText(_translate("MainWindow", "threshold"))
        self.Comp_ratio_label.setText(_translate("MainWindow", "ratio"))
        self.Comp_makeup_label.setText(_translate("MainWindow", "makeup"))
        self.Comp_threshold_lineEdit.setText(_translate("MainWindow", "90"))
        self.dB_Comp.setText(_translate("MainWindow", "dB"))
        self.Comp_ratio_lineEdit.setText(_translate("MainWindow", "5"))
        self.Comp_makeup_lineEdit.setText(_translate("MainWindow", "0"))
        self.dB_Comp_2.setText(_translate("MainWindow", "dB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
